apiVersion: v1
kind: Pod
metadata:
  name: adlink-pod
spec:
  containers:
    - name: adlink-container
      image: k3306361/adlink
      command:
        - sleep
        - infinity
      securityContext:
        privileged: true
      env:
        - name: DISPLAY
          value: ":0"
      volumeMounts:
        - name: x11-socket
          mountPath: /tmp/.X11-unix
        - name: video0
          mountPath: /dev/video0
  volumes:
    - name: x11-socket
      hostPath:
        path: /tmp/.X11-unix
    - name: video0
      hostPath:
        path: /dev/video0
