apiVersion: v1
kind: Pod
metadata:
  name: facial-recognition-pod
spec:
  containers:
    - name: -container
      image: k3306361/facial_recognition
      command:
        - sleep
        - infinity
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_RAWIO
            - SYS_I2C
            - SYS_ADMIN
